teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false

    axis_linear:
      x: 1     # axe vertical du stick gauche (repéré par /joy)
      y: 0     # inutilisé → 0 ou -1
      z: 0     # inutilisé → 0

    scale_linear:
      x: 0.2   # vitesse linéaire max (m/s)
      y: 0.0   # inutilisé
      z: 0.0   # inutilisé

    scale_linear_turbo:
      x: 0.5  # vitesse boostée

    axis_angular:
      yaw:   0  # axe horizontal du stick gauche (repéré par /joy)
      pitch: 0  # inutilisé
      roll:  0  # inutilisé

    scale_angular:
      yaw:   1.0  # vitesse angulaire max (rad/s)
      pitch: 0.0
      roll:  0.0

    scale_angular_turbo:
      yaw: 2.0  # rotation plus rapide en turbo

    enable_turbo_button: 6  # ex: bouton L1 sur une manette PS (vérifie avec rostopic echo /joy)

    inverted_reverse: false           # laisser à false pour un Kobuki
    publish_stamped_twist: false      # on publie un Twist non horodaté
